### ISSUE TITLE
Prompts to get folks to think

### ISSUE THREAD

**Issue by knowtheory** [BadIdeaFactory/truthgoggles#1] opened 2017-12-30 16:51 UTC
Fact checking systems all have a major delivery challenge.  Fact checking is a mechanism, it's not an end to itself.  So the primary question facing us is what sorts of ends can we bend fact checking to?  What are the motivations which drive a need that can be solved, improved or augmented with fact checking?

@Slifty's primary frame for this has been a metaphorical drinking buddy who can talk to you about a thing you feel strongly about.

@knowtheory also mentioned the frame is how can we tap into people's pride and have a system that checks what they share and retweet and tells them how gullible they are.

But at its core the question is how are conversations for others mediated where a tool is useful on the one hand, or alternatively, is it possible to let some people opt into a reading experience which gives them additional reference points (and maybe fun?)

**Comment by slifty** [comment] 2018-05-01 15:08
Our thinking has coalesced a bit and even resulted in a [great presentation](https://www.slideshare.net/biffud/truth-goggles-2)!

Still room for thinking prompts in this project I suppose, but as far as the issue is concerned we can close it.

**Closed by slifty** 2018-05-01 15:08 UTC
